using Priority_Queue;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace TSP
{
    class State : PriorityQueueNode 
	{
		# region static members
		private static int numCities;
		#endregion

		# region private members
		private ArrayList tour;
		private double[,] costMatrix;
		private double cost;
		private double bound;
		#endregion 

		#region Constructors

		public State() { }

		/// <summary> creates the start state from a list of cities </summary>
		/// <param name="iRoute"> the list of cities generated by the solver </param>
		public State(ArrayList iRoute)
		{
			numCities = iRoute.Count;

			tour = new ArrayList();
			cost = 0;
			bound = 0;

			costMatrix = new double[iRoute.Count, iRoute.Count];
			for (int i = 0; i < iRoute.Count; ++i)
			{
				City current = iRoute[i] as City;
				for (int j = i; j < iRoute.Count; ++j)
				{
					double currCost = current.costToGetTo(iRoute[j] as City);
					if (i == j) // on the diagonal
						currCost = double.MaxValue;
					costMatrix[i, j] = currCost;
					costMatrix[j, i] = costMatrix[i, j];
				}
			}
			reduceMatrix();
		}
		#endregion

		# region private methods
		/// <summary> 
		///  reduces the costMatrix
		///  subtracts the minimum from each row and column and adds it to the bound
		/// </summary>
		// TO DO: eliminate impossible edges
		private void reduceMatrix() 
		{
			// reduce each row
			for (int i = 0; i < numCities; ++i)
			{
				double min = double.MaxValue;
				for (int j = 0; j < numCities; ++j)
				{
					if (costMatrix[i, j] < min)
						min = costMatrix[i, j];
				}
				if (min != 0 && min != double.MaxValue)
				{
					for (int j = 0; j < numCities; ++j)
					{
						if (costMatrix[i,j] != double.MaxValue) // don't reduce the infinities
							costMatrix[i, j] -= min;
					}
				}
				bound += min;
			}
			// reduce each column
			for (int j = 0; j < numCities; ++j)
			{
				double min = double.MaxValue;
				for (int i = 0; i < numCities; ++i)
				{
					if (costMatrix[i, j] < min)
						min = costMatrix[i, j];
				}
				if (min != 0 && min != double.MaxValue)
				{
					for (int i = 0; i < numCities; ++i)
					{
						if (costMatrix[i, j] != double.MaxValue) // don't reduce the infinities
							costMatrix[i, j] -= min;
					}
				}
				bound += min;
			}
		}
		#endregion
	}
}
